
AUTH_POPUP_PASSWORD = "admin"
AUTH_POPUP_USERNAME = "admin"

URL_ADMIN_DEMO = "https://admin-demo.nopcommerce.com/login"
URL_AUTH_POPUP = "https://the-internet.herokuapp.com/basic_auth"
URL_AUTOMATION_PRACTICE = "http://automationpractice.com/index.php"
URL_COUNTRIES_OF_THE_WORLD = "https://www.countries-ofthe-world.com/flags-of-the-world.html"
URL_DATEPICKER_STANDARD = "https://jqueryui.com/datepicker/"
URL_DEAD_LINK_CITY = "http://www.deadlinkcity.com/"
URL_DEMO_NOPCOMMERCE = "https://demo.nopcommerce.com/login"
URL_DRAG_AND_DROP_DEMO = "http://dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html"
URL_DUMMY_TICKET_WEBSITE = "https://www.dummyticket.com/"
URL_FILE_DOWNLOAD_EXAMPLES = "https://file-examples.com/index.php/sample-documents-download/sample-doc-download/"
URL_INNER_FRAMES = "http://demo.automationtesting.in/Frames.html"
URL_JAVASCRIPT_ALERTS = "https://the-internet.herokuapp.com/javascript_alerts"
URL_JQUERY_SLIDER_EX = "https://www.jqueryscript.net/demo/Price-Range-Slider-jQuery-UI/"
URL_MONEY_GAINERS = "https://money.rediff.com/gainers/bse/daily/groupa"
URL_OPENCART = "https://www.opencart.com/index.php?route=account/register"
URL_ORANGEHRM = "https://opensource-demo.orangehrmlive.com/"
URL_POPUP_ALERTS = "https://mypage.rediff.com/login/dologin"
URL_POPUP_WHAT_MY_LOCATION = "https://whatmylocation.com/"
URL_SELENIUM_DOC_FRAME = "https://www.selenium.dev/selenium/docs/api/java/index.html?overview-summary.html"
URL_SNAPDEAL = "http://www.snapdeal.com"
URL_TEXT_COMPARE = "https://text-compare.com"
URL_WEBTABLE_DYNAMIC = URL_ORANGEHRM
URL_WEBTABLE_STATIC = "https://testautomationpractice.blogspot.com/"
URL_WEB_ELEMENTS_PRACTICE_FORM = "https://itera-qa.azurewebsites.net/home/automation"